# The URL the site will be built for
base_url = "https://nilueps.net"

title = "Nicolas Epstein"
description = "Personal website of Nicolas Lucino Epstein"

default_language = "en"

generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

ignored_content = ["*.backup"]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
# highlight_theme_css = [
#   { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
#   { theme = "gruvbox-light", filename = "syntax-theme-light.css" }
# ]

# external_links_target_blank = true
smart_punctuation = true


[extra]
# Put all your custom variables here
